name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests with TestNG
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml -Dmaven.test.failure.ignore=true -Dlog.level=info

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages with History
        if: success()
        run: |
          git config --global user.email "aleksandar.stojanovic@qakursevionline.com"
          git config --global user.name "Aleksandar Stojanovic"
          
          # Clone gh-pages branch
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          
          # Copy the existing history directory if it exists
          mkdir -p allure-history
          if [ -d "gh-pages/history" ]; then
            cp -r gh-pages/history allure-history/
          fi

          # Clean the old report files
          rm -rf gh-pages/*

          # Copy new report to gh-pages
          cp -r target/site/allure-maven-plugin/* gh-pages/

          # Reintegrate the history back into the new report
          if [ -d "allure-history" ]; then
            cp -r allure-history/* gh-pages/history/
          fi

          # Push the updated report to gh-pages
          cd gh-pages
          git add .
          git commit -m "Update Allure Report with History"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
